apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: sjl17z4na-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:d6d5496d6b224425cd0096406f30d2627c7b692f@sha256:47ad43c3414e981b0cfe90c02668f694f0ec213e6387ac0f0c1cc63984c161d9
        name: container-image  
